
 public enum Type {
       
	   LPAREN, RPAREN, IDENT, ATOM, PROGRAM, ENDCOMMENT, 
       VAR, PLUS, MINUS, TIMES, EQL,COMMA,SEMICOLON,SLASH,TRUESYM,NUMLIT,
       ASSIGN_OP, LSS, LEQ, GTR, GEQ, BEGINSYM, BOOLSYM, ELSESYM,ENDSYM,FALSESYM,
       GETSYM,IFSYM, NAL, INTEGER,COLON,BEGIN,CONST,WRITE,MOD,END,SINQUO,READ,DIV,
       THENSYM,QUOTE,UNKNOWN,BEGCOMMENT,WHILE,FOR,TO,DO;
    }
 
 //holds tokens via enumerated type